package org.apache.cayenne.osgi.example.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Entity2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Entity2 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String AMOUNT_PROPERTY = "amount";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> AMOUNT = new Property<Integer>("amount");

    public void setAmount(Integer amount) {
        writeProperty("amount", amount);
    }
    public Integer getAmount() {
        return (Integer)readProperty("amount");
    }

}
